name: 163Music

on:
  workflow_dispatch:
  push:
    branches: [ master ]
#   pull_request:
#     branches: [ master ]
  schedule:
    - cron: 15 1 * * *

jobs:
  check-in:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install Python
      run: |
        sudo apt update && \
        sudo apt install python3
      
    - name: requirements
      run: |
        pip3 install -r requirements.txt
        
    - name: Checkin
      env: # Or as an environment variable
        netease_username: ${{ secrets.USER }}
        netease_password: ${{ secrets.PWD }}
      run: |
        echo "hello"
        echo $netease_username
        python3 music.py
